### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by vangeest** [informatica-emmauscollege/algoritmiek-opdrachten#1]
Zullen we deze repo renamen volgens de conventie
jaar-laag-module-toevoeging?

Dus: 1920-4HV-algoritmen-opdrachten

PS. ik durfde de Rename niet zomaar door te voeren, omdat linken naar de repo dan veranderen en ik weet niet in hoeverre je die al gebruikt had. Het maken van een pull-request kon ook niet, omdat de naam vd repo niet in een branche zit.

**Comment by cam-emmauscollege** [comment]
Prima, doe maar gelijk

**Comment by vangeest** [comment]
Done.
